# Generated by Django 4.2.29 on 2026-08-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField()),
                ('description', models.TextField()),
                ('birthday', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('degree', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('freelance', models.CharField(blank=True, max_length=100)),
                ('bottom_description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='startingpage',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
