# Generated by Django 4.2.29 on 2026-08-24 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_education_experience_resumesummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceResponsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibilities', to='apps.experience')),
            ],
        ),
    ]
