# Generated by Django 4.2.29 on 2026-08-24 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_experienceresponsibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='description',
        ),
    ]
