# Generated by Django 4.2.29 on 2026-08-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_technicalskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalskill',
            name='icon',
            field=models.CharField(blank=True, help_text='Example: bi-broadcast', max_length=100),
        ),
    ]
