# Generated by Django 4.2.29 on 2026-08-24 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_technicalskill_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicalskill',
            name='description',
        ),
        migrations.CreateModel(
            name='MainTechnicalSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('technical_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_data', to='apps.technicalskill')),
            ],
        ),
    ]
