# Generated by Django 4.2.29 on 2026-08-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_remove_technicalskill_description_maintechnicalskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('web', 'Web Development'), ('network', 'Network & IT'), ('django', 'Django'), ('python', 'Python'), ('other', 'Other')], default='other', max_length=50)),
                ('image', models.ImageField(upload_to='projects/')),
                ('description', models.TextField()),
                ('project_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
