# Generated by Django 4.2.29 on 2026-08-25 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonFormalEducationTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NonFormalEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('start_year', models.CharField(max_length=20)),
                ('end_year', models.CharField(max_length=20)),
                ('institution', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_data', to='apps.nonformaleducationtitle')),
            ],
        ),
    ]
