# Generated by Django 4.2.29 on 2026-08-25 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_nonformaleducationtitle_nonformaleducation'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonFormalEducationCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='nonformaleducation',
            name='title',
        ),
        migrations.DeleteModel(
            name='NonFormalEducationTitle',
        ),
        migrations.AlterField(
            model_name='nonformaleducation',
            name='course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_data', to='apps.nonformaleducationcourse'),
        ),
    ]
