# Generated by Django 4.2.29 on 2026-08-25 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_nonformaleducationcourse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonformaleducation',
            name='end_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
