# Generated by Django 4.2.29 on 2026-08-25 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_alter_nonformaleducation_end_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nonformaleducation',
            old_name='course_name',
            new_name='course',
        ),
    ]
