# Generated by Django 4.2.29 on 2026-08-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_rename_course_name_nonformaleducation_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nonformaleducation',
            options={'ordering': ['-start_year']},
        ),
        migrations.AlterField(
            model_name='nonformaleducation',
            name='end_year',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nonformaleducation',
            name='start_year',
            field=models.IntegerField(max_length=20),
        ),
    ]
