# Generated by Django 4.2.29 on 2026-08-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_alter_nonformaleducation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nonformaleducation',
            options={},
        ),
        migrations.AlterField(
            model_name='nonformaleducation',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nonformaleducation',
            name='start_year',
            field=models.IntegerField(),
        ),
    ]
