# Generated by Django 4.2.29 on 2026-09-05 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_alter_nonformaleducation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/services/')),
                ('icon', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/web/')),
                ('year', models.PositiveIntegerField()),
                ('technologies', models.CharField(blank=True, max_length=500)),
                ('case_study_url', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
