# Generated by Django 5.2.17 on 2026-10-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_projectservice_projectweb'),
    ]

    operations = [
        migrations.AddField(
            model_name='startingpage',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
